title:              Life of a Modern Man
email:              vonfreiren@protonmail.com
description:        Advising in Lifestyle and Finance

author:             Javier Freire
baseurl:            ""
url:                "https://mrfreire.net"

# Social Profiles
github_username:    vonfreiren
instagram_username: vonfreiren
linkedin_username:  javfreire
medium_username: javier-freire
rss: RSS

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-LXEKPLTM1K # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter:        rouge
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache


tag_page_layout: tag_page
tag_page_dir: tag

collections:
  books:
  concerts:
  courses:
    sort_by: name
    sort_order: ascending
  spanish:
    output: true
    sort_by: date
    sort_order: descending

  french:
    output: true
    sort_by: date
    sort_order: descending

  german:
    output: true
    sort_by: date
    sort_order: descending

feed:
  title: Life of a Modern Man
  description: Advising in Lifestyle and Finance
  url: https://mrfreire.net/feed.xml

defaults:
  -
    scope:
      path:            "tag"
    values:
      sitemap:         false
  - scope:
      path:             "posts"
    values:
      sitemap:          false


tag_permalink_style: pretty

permalink: pretty

i18n.locale: 'es'


en:
  label: English
  icon: 🇬🇧
  read_it_in: "Read it in"
es:
  label: Español
  icon: 🇪🇸
  read_it_in: "Léelo en"