title:              Modern's Man Life
email:              vonfreiren@protonmail.com
description:        A Blog about different topics of life
author:             Javier Freire
baseurl:            ""
url:                "https://vonfreiren.github.io"

# Social Profiles
twitter_username:   vonfreiren
github_username:    vonfreiren
facebook_username:  vonfreiren
instagram_username: vonfreiren
linkedin_username:  jfreirea

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-LXEKPLTM1K # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
