title:              The Life of a Modern Man
email:              vonfreiren@protonmail.com
description:        Improvements in Lifestyle and Finance
author:             Javier Freire
baseurl:            ""
url:                "https://mrfreire.net"

# Social Profiles
twitter_username:   vonfreiren
github_username:    vonfreiren
facebook_username:  vonfreiren
instagram_username: vonfreiren
linkedin_username:  jfreirea
rss: RSS

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-LXEKPLTM1K # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag



tag_permalink_style: pretty

permalink: pretty
