title:              Life of a Modern Man
email:              vonfreiren@protonmail.com
description:        Advising in Lifestyle and Finance

author:             Javier Freire
baseurl:            ""
url:                "https://mrfreire.net"

# Social Profiles
twitter_username:   vonfreiren
github_username:    vonfreiren
facebook_username:  vonfreiren
instagram_username: vonfreiren
linkedin_username:  javfreire
medium_username: mr-freire
rss: RSS

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-LXEKPLTM1K # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: rouge
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path:            "tag"
    values:
      sitemap:         false
  - scope:
      path:             "posts"
    values:
      sitemap:          false


tag_permalink_style: pretty

permalink: pretty


en:
  label: English
  icon: 🇬🇧
  read_it_in: "Read it in"
es:
  label: Español
  icon: 🇪🇸
  read_it_in: "Léelo en"